config/routes.rb
Rails.application.routes.draw do
  root "subs#index"
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    member do
      post "upvote"
      post "downvote"
    end
    resources :comments, except: :index do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end
end

app/views/partials/_comment.html.erb
<p>
<%= comment.score %>
<%= vote_button(upvote_post_comment_url(comment.post_id, comment), "^") %>
<%= vote_button(downvote_post_comment_url(comment.post_id, comment), "v") %>
<b><%= comment.author.user_name %></b>,
  <i><%= formatted_date(comment.updated_at) %></i>
  <% if current_user == comment.author %>
    <a href="<%= edit_post_comment_url(comment.post_id, comment) %>">edit</a>
  <% end %>
  <a href="<%= post_comment_url(comment.post_id, comment) %>">view</a>
</p>

<p><%= comment.content %></p>

<ul>
  <% comment_hash[comment.id].each do |child_comment| %>
    <li><%= render "partials/comment", comment: child_comment, comment_hash: comment_hash %></li>
  <% end %>
</ul>
<!-- <hr> -->

app/views/partials/_comment_form.html.erb
<% if action == :edit %>
  <input type="hidden" name="_method" value="patch">
<% end %>

<% if action == :reply %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= parent_id %>">
<% end %>

<input type="hidden" name="comment[post_id]" value=" <%= post_id %>">

<label for="comment_content">Comment:</label>
<br>
<textarea
  id="comment_content"
  name="comment[content]"
  rows="8"
  cols="40"><%= comment.content %></textarea>
<br>
<button>Submit</button>

app/views/partials/_post_form.html.erb
<label>Subreddits:</label>
<br>
<input type="hidden" name="post[sub_ids][]" value="">
<% Sub.all.each do |sub| %>
  <input
    type="checkbox"
    name="post[sub_ids][]"
    value="<%= sub.id %>"
    <%= "checked" if post.subs.include?(sub) %>>
    <%= sub.title %>
    <br>
<% end %>
<br>
<label for="post_title">Title:</label>
<input id="post_title"
       type="text"
       name="post[title]"
       value="<%= post.title %>">
<br>
<label for="post_url">URL:</label>
<input id="post_url"
       type="text"
       name="post[url]"
       value="<%= post.url %>">
<br>
<label for="post_content">Content:</label>
<textarea id="post_content"
          name="post[content]"
          rows="8"
          cols="40"><%= post.content %></textarea>

app/views/partials/_sub_form.html.erb
<label for="sub_title">Title:</label>
<input id="sub_title"
       type="text"
       name="sub[title]"
       value="<%= sub.title %>"
       placeholder="funny">
<br>
<label for="sub_description">Description:</label>
<textarea id="sub_description"
          name="sub[description]"
          rows="8"
          cols="40"><%= sub.description %></textarea>
<br>   

app/views/partials/_user_form.html.erb
<label for="user_user_name">Username:</label>
<input id="user_user_name"
       type="text"
       name="user[user_name]"
       placeholder="username">
<br>
<label for="user_password">Password:</label>
<input id="user_password"
       type="password"
       name="user[password]">
<br>