config/routes.rb
Rails.application.routes.draw do
  root "subs#index"
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    member do
      post "upvote"
      post "downvote"
    end
    resources :comments, except: :index do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator, class_name: "User"
  has_many :post_subs, dependent: :destroy
  has_many :posts, through: :post_subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def new
    @sub = Sub.new
  end

  def create
    @sub = current_user.moderated_subs.new(sub_params)

    if @sub.save
      flash[:notice] = "Successfully created #{@sub.title}"
      redirect_to root_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      flash[:notice] = "Your changes have been recorded"
      redirect_to root_url
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy!
    redirect_to root_url
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.includes(posts: :author).find(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %>!</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= form_auth_token %>
  <input type="hidden" name="_method" value="patch">
  <%= render "partials/sub_form", sub: @sub %>
  <button>Edit Sub</button>
</form>

app/views/subs/index.html.erb
<h1>Welcome to Reddit, front page of the internet</h1>

<a href="<%= new_sub_url %>">Create a sub</a>
<br>
<%= flash_notices %>

<h3>All subs</h3>
<ul>
<% @subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>Make a new Sub!</h1>
<%= flash_errors %>
<br><br>
<form action="<%= subs_url %>" method="post">
  <%= form_auth_token %>
  <%= render "partials/sub_form", sub: @sub %>
  <button>Create Sub</button>
</form>

app/views/subs/show.html.erb
<a href="<%= root_url %>"><< HOME</a>

<h1> <%= @sub.title %> </h1>
<%= flash_notices %>
<p><%= @sub.description %></p>

<% if current_user == @sub.moderator %>
  <a href="<%= edit_sub_url(@sub) %>">Edit sub</a>
  <%= delete_button(sub_url(@sub), "Remove Sub") %>
<% end %>


<h3>Posts</h3>
<a href="<%= new_post_url %>">New Post</a>

<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <%= post.score %>
      <%= vote_button(upvote_post_url(post), "^") %>
      <%= vote_button(downvote_post_url(post), "v") %>
      <a href="<%= post_url(post) %>"><%= post.title %></a>
      by: <%= post.author.user_name %>
    </li>
  <% end %>
</ul>