config/routes.rb
Rails.application.routes.draw do
  root "subs#index"
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    member do
      post "upvote"
      post "downvote"
    end
    resources :comments, except: :index do
      member do
        post "upvote"
        post "downvote"
      end
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Votable
  
  validates :title, :author_id, presence: true

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments, dependent: :destroy

  belongs_to :author, class_name: "User"

  def comments_by_parent_id
    comment_hash = Hash.new { |h, k| h[k] = [] }

    comments.each do |comment|
      comment_hash[comment.parent_comment_id] << comment
    end

    comment_hash
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Post was successfully created"
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = "Your changes have been recorded"
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to root_url
  end

  def index
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote!
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote!
    redirect_to :back
  end

  def show
    @post = Post.includes(:subs, comments: [:post, :child_comments, :author]).find(params[:id])
    @comment_hash = @post.comments_by_parent_id
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>
  <%= flash_errors %>
<form action="<%= post_url(@post) %>" method="post">
    <%= form_auth_token %>
    <input type="hidden" name="_method" value="patch">
    <%= render "partials/post_form", post: @post%>
    <button>Submit edit</button>
</form>

app/views/posts/new.html.erb
<h1>Make a new post</h1>
<%= flash_errors %>
<br><br>
<form action="<%= posts_url %>" method="post">
    <%= form_auth_token %>
    <%= render "partials/post_form", post: @post%>
    <button>Submit</button>
</form>

app/views/posts/show.html.erb
<a href="<%= root_url %>"><< HOME</a>
<ul>
  <% @post.subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

<h1><%= @post.title %></a></h1>
<p>by: <b><%= @post.author.user_name %></b></p>
<p>
  <%= vote_button(upvote_post_url(@post), "^") %>
  <%= vote_button(downvote_post_url(@post), "v") %>
</p>
<p><%= @post.url  %></p>
<p><%= @post.content %></p>

<% if current_user == @post.author %>
  <a href="<%= edit_post_url(@post) %>">Edit post</a>
  <%= delete_button(post_url(@post), "Remove Post") %>
<% end %>

<br><br>

<form action="<%= post_comments_url(@post) %>" method="post">
  <%= form_auth_token %>
  <%= render "partials/comment_form", action: :new,
                                      comment: Comment.new,
                                      post_id: @post.id %>
</form>

<br>
<% @comment_hash[nil].each do |comment| %>
  <%= render "partials/comment", comment: comment, comment_hash: @comment_hash %>
<% end %>